### ISSUE TITLE
Plugin configured with CI metrics prevents logs from being displayed in the pipeline stage view

### ISSUE THREAD

**Issue by DaniJG** [jenkinsci/datadog-plugin#324]
**Describe the bug**
Logs normally displayed within the [Pipeline stage view](https://plugins.jenkins.io/pipeline-stage-view/) are no longer visible once the datadog plugin is installed and CI visibility is enabled as per [official datadog docs](https://docs.datadoghq.com/continuous_integration/pipelines/jenkins/?tab=usingenvironmentvariables#enabling-ci-visibility-on-the-plugin).

Each of the stages will display the logs while the job is running, but as soon as the job finishes the logs modal becomes empty. This continues until the jenkins server is restarted, at which point you can see the logs for existing jobs (but will have the same issue for any newly triggered jobs)

**To Reproduce**
1. In Jenkins 2.375.2 install the workflow-job, workflow-aggregator and datadog plugins with versions noted below
2. Configure the datadog plugin to send CI metrics as per [official datadog docs](https://docs.datadoghq.com/continuous_integration/pipelines/jenkins/?tab=usingenvironmentvariables#enabling-ci-visibility-on-the-plugin). (If you just install the plugin without configuring it, the issue disappears)
3. Create a Jenkins pipeline with stages: <img width="1422" alt="Screenshot 2023-01-23 at 19 06 28" src="https://user-images.githubusercontent.com/3903889/214121175-efce9e26-3bac-43d5-aa17-60ac50d18fcf.png">
4. Run the pipeline
5. In the pipeline view, note you see the logs fore each stage **while the job is still running**: <img width="1645" alt="Screenshot 2023-01-23 at 19 06 44" src="https://user-images.githubusercontent.com/3903889/214121185-fcf3c840-ae9b-48f5-b2a6-f576aa2c6aa3.png">
6. As soon as the job finishes, the logs for each stage can no longer be seen: <img width="1644" alt="Screenshot 2023-01-23 at 19 30 32" src="https://user-images.githubusercontent.com/3903889/214121183-2c4f4fc7-3274-4ef6-ac26-926d9235b292.png"> (There are no errors in the browser console nor network tab)
7. If the server is restarted, the logs are visible again in the pipeline view. However, the error will repeat itself for any newly run jobs)

**Expected behavior**
The logs should continue to be visible in the pipeline view, even when the datadog plugin is installed and configured to capture CI metrics. Ie, after step 6 above (job finishes), the logs should continue to be visible in the pipeline view.

**Environment and Versions (please complete the following information):**
- jenkins: 2.375.2 (container jenkins/jenkins:2.375.2-lts)
- datadog-plugin: 5.2.0
- pipeline-stage-view: 2.29
- workflow-job: 1268.v6eb_e2ee1a_85a
- workflow-aggregator: 590.v6a_d052e5a_a_b_5 

**Additional context**
- Datadog plugin configured to track CI metrics using environment variables:
    ```
    - name: DATADOG_JENKINS_PLUGIN_REPORT_WITH
      value: DSD
    - name: DATADOG_JENKINS_PLUGIN_TARGET_HOST
      value: datadog.datadog-agent.svc.cluster.local
    - name: DATADOG_JENKINS_PLUGIN_TARGET_PORT
      value: "8125"
    - name: DATADOG_JENKINS_PLUGIN_ENABLE_CI_VISIBILITY
      value: "true"
    - name: DATADOG_JENKINS_PLUGIN_TARGET_TRACE_COLLECTION_PORT
      value: "8126"
    - name: DATADOG_JENKINS_PLUGIN_CI_VISIBILITY_CI_INSTANCE_NAME
      value: jenkins-test
    ```
- Log injection is not enabled in the datadog plugin. Ie, I haven't applied the optional steps https://docs.datadoghq.com/continuous_integration/pipelines/jenkins/?tab=usingenvironmentvariables#enable-job-log-collection
- I have tried downgrading the datadog plugin to versions `4.0.0`, `3.5.2` and `2.13.0`. The problem still persists.
- Both jenkins and datadog agent hosted in Kubernetes. Jenkins deployed with the jenkins-operator and the datadog agent with the official helm chart.

**Comment by albertvaka** [comment]
This should now be fixed in the Datadog Plugin for Jenkins version 5.3.0 which was just released.

**Comment by DaniJG** [comment]
I just tested the new version 5.3.0 of the plugin, but I still have the same issue. While the job is running, I can see the logs for each pipeline stage. As soon as the job finishes, the logs do not show up.

Note I dont have log injection enabled in the plugin. I am only enabling the collection of CI metrics.

Checking the browser dev tools, I can see that while the job runs, each of the `stageFlowNodes` contains `_links.logs` and `_links.console` in addition to `_links.self`.
<img width="1017" alt="Screenshot 2023-02-16 at 11 50 48" src="https://user-images.githubusercontent.com/3903889/219345578-9d6c1b94-c210-42a4-9ce7-e0b1e5e67c55.png">

Once the job has finished, each of the `stageFlowNodes` just contains `_links.self`.
<img width="1019" alt="Screenshot 2023-02-16 at 11 53 38" src="https://user-images.githubusercontent.com/3903889/219345615-463e41a9-2539-46ce-9081-bced4ecbb3a9.png">

That feels related or a symptom of the problem, but I dont really know the jenkins codebase well enough to judge further.

--- 

Let me know if I can get you any further information to reproduce.

There are no errors in the console that I can see. And in case it helps, here is the full list of plugins I have just tried with the upgraded datadog plugin:
```
OkHttp Plugin (okhttp-api): 4.10.0-117.vf786fdfa_22c0
JavaBeans Activation Framework (JAF) API (javax-activation-api): 1.2.0-5
Plugin Utilities API Plugin (plugin-util-api): 2.20.0
Pipeline: Declarative (pipeline-model-definition): 2.2118.v31fd5b_9944b_5
JavaMail API (javax-mail-api): 1.6.2-5
commons-lang3 v3.x Jenkins API Plugin (commons-lang3-api): 3.12.0-36.vd97de6465d5b_
Pipeline: Model API (pipeline-model-api): 2.2118.v31fd5b_9944b_5
Pipeline: Supporting APIs (workflow-support): 839.v35e2736cfd5c
Folders Plugin (cloudbees-folder): 6.800.v71307ca_b_986b
Jakarta Mail API (jakarta-mail-api): 2.0.1-2
GitHub Branch Source Plugin (github-branch-source): 1701.v00cc8184df93
Pipeline: Stage View Plugin (pipeline-stage-view): 2.31
Pipeline: Input Step (pipeline-input-step): 466.v6d0a_5df34f81
Slack Notification Plugin (slack): 631.v40deea_40323b
Mailer Plugin (mailer): 448.v5b_97805e3767
SnakeYAML API Plugin (snakeyaml-api): 1.33-90.v80dcb_3814d35
Pipeline: Milestone Step (pipeline-milestone-step): 111.v449306f708b_7
Active Directory plugin (active-directory): 2.30
Kubernetes Credentials Plugin (kubernetes-credentials): 0.10.0
Pipeline: Groovy Libraries (pipeline-groovy-lib): 629.vb_5627b_ee2104
Pipeline: Stage Tags Metadata (pipeline-stage-tags-metadata): 2.2118.v31fd5b_9944b_5
jnr-posix API Plugin (jnr-posix-api): 3.1.16-1
Durable Task Plugin (durable-task): 504.vb10d1ae5ba2f
Jakarta Activation API (jakarta-activation-api): 2.0.1-2
JUnit Plugin (junit): 1177.v90374a_ef4d09
SCM API Plugin (scm-api): 631.v9143df5b_e4a_a
Caffeine API Plugin (caffeine-api): 2.9.3-65.v6a_47d0f4d1fe
Ionicons API (ionicons-api): 31.v4757b_6987003
bouncycastle API Plugin (bouncycastle-api): 2.27
Trilead API Plugin (trilead-api): 2.84.v72119de229b_7
Instance Identity (instance-identity): 142.v04572ca_5b_265
Git plugin (git): 5.0.0
ECharts API Plugin (echarts-api): 5.4.0-1
Pipeline: REST API Plugin (pipeline-rest-api): 2.31
Pipeline: SCM Step (workflow-scm-step): 400.v6b_89a_1317c9a_
GitHub plugin (github): 1.36.1
Configuration as Code Plugin (configuration-as-code): 1569.vb_72405b_80249
Kubernetes Credentials Provider (kubernetes-credentials-provider): 1.209.v862c6e5fb_1ef
SSH server (sshd): 3.236.ved5e1b_cb_50b_2
Job DSL (job-dsl): 1.81
Git client plugin (git-client): 4.1.0
Popper.js 2 API Plugin (popper2-api): 2.11.6-2
Pipeline: Job (workflow-job): 1268.v6eb_e2ee1a_85a
Pipeline: Build Step (pipeline-build-step): 2.18.1
Kubernetes plugin (kubernetes): 3852.v41ea_166a_ed1b_
Metrics Plugin (metrics): 4.2.13-420.vea_2f17932dd6
commons-text API Plugin (commons-text-api): 1.10.0-27.vb_fa_3896786a_7
JQuery3 API Plugin (jquery3-api): 3.6.1-2
Java JSON Web Token (JJWT) Plugin (jjwt-api): 0.11.5-77.v646c772fddb_0
Authentication Tokens API Plugin (authentication-tokens): 1.4
Script Security Plugin (script-security): 1229.v4880b_b_e905a_6
Pipeline: Groovy (workflow-cps): 3618.v13db_a_21f0fcf
Credentials Binding Plugin (credentials-binding): 523.vd859a_4b_122e6
JAXB plugin (jaxb): 2.3.8-1
Pipeline: Step API (workflow-step-api): 639.v6eca_cd8c04a_a_
Plain Credentials Plugin (plain-credentials): 143.v1b_df8b_d3b_e48
Pipeline: Declarative Extension Points API (pipeline-model-extensions): 2.2118.v31fd5b_9944b_5
Display URL API (display-url-api): 2.3.7
SSH Credentials Plugin (ssh-credentials): 305.v8f4381501156
Handy Uri Templates 2.x API Plugin (handy-uri-templates-2-api): 2.1.8-22.v77d5b_75e6953
Pipeline (workflow-aggregator): 590.v6a_d052e5a_a_b_5
Datadog Plugin (datadog): 5.3.0
Pipeline: Basic Steps (workflow-basic-steps): 994.vd57e3ca_46d24
Token Macro Plugin (token-macro): 321.vd7cc1f2a_52c8
Pipeline Utility Steps (pipeline-utility-steps): 2.15.0
Kubernetes Client API Plugin (kubernetes-client-api): 6.3.1-206.v76d3b_6b_14db_b
Bitbucket Branch Source Plugin (cloudbees-bitbucket-branch-source): 791.vb_eea_a_476405b
Structs Plugin (structs): 324.va_f5d6774f3a_d
Pipeline: Nodes and Processes (workflow-durable-task-step): 1223.v7f1a_98a_8863e
Credentials Plugin (credentials): 1214.v1de940103927
Pipeline: Stage Step (pipeline-stage-step): 305.ve96d0205c1c6
Font Awesome API Plugin (font-awesome-api): 6.2.1-1
Variant Plugin (variant): 59.vf075fe829ccb
Mina SSHD API :: Common (mina-sshd-api-common): 2.9.2-50.va_0e1f42659a_a
Branch API Plugin (branch-api): 2.1071.v1a_188a_562481
Apache HttpComponents Client 4.x API Plugin (apache-httpcomponents-client-4-api): 4.5.13-138.v4e7d9a_7b_a_e61
Pipeline: Multibranch (workflow-multibranch): 733.v109046189126
Bootstrap 5 API Plugin (bootstrap5-api): 5.2.1-3
Checks API plugin (checks-api): 1.8.1
GitHub API Plugin (github-api): 1.303-400.v35c2d8258028
Jackson 2 API Plugin (jackson2-api): 2.14.2-319.v37853346a_229
Pipeline: API (workflow-api): 1208.v0cc7c6e0da_9e
Mina SSHD API :: Core (mina-sshd-api-core): 2.9.2-50.va_0e1f42659a_a
Pipeline Graph Analysis Plugin (pipeline-graph-analysis): 202.va_d268e64deb_3
```

**Comment by sarah-witt** [comment]
Hi @DaniJG, sorry for the delay in resolution. We've done some more testing and believe we have a workaround in place. Do you mind trying to set the property `DATADOG_CACHE_BUILD_RUNS` to `false`? Thanks!

**Comment by DaniJG** [comment]
Thanks @sarah-witt, the workaround worked!

Any side effects or downsides setting that config value to false?

**Comment by sarah-witt** [comment]
That's great to hear! Enabling this option avoids utilizing the cached build runs when we calculate information about them, so enabling it may have a small performance impact, but it should not have any major effects. We plan to do some more research into this behavior in the future.

**Comment by DaniJG** [comment]
Awesome, thanks for confirming! Happy to close the issue, since I have a viable workaround that unblocks us. 

if you find at some point a fix that doesn't require the workaround let me know

**Comment by sarah-witt** [comment]
Sure, will do!
